Feat/newsfeed
wafflestudio19-5/team9-server pull request #11
Opened 2021-12-02 11:08 UTC by jaejae2374

2021-12-02 11:13 UTC, IHIHHIHI commented
넵. 그리고 지금처럼 문제가 있는 경우에는 풀 리퀘스트를 다시 날릴 필요 없이 작업하시는 브랜치에 커밋 날려주시면 반영됩니다!

2021-12-02 11:14 UTC, IHIHHIHI commented
그리고 여전히 스태틱 파일도 보입니다..!

2021-12-02 11:31 UTC, leejoey0921 commented
일단 Actions에 makemigration 추가해서 일단 test DB 생성 관련된 문제는 해결한 것 같습니다!

2021-12-02 11:46 UTC, leejoey0921 commented
> 일단 Actions에 makemigration 추가해서 일단 test DB 생성 관련된 문제는 해결한 것 같습니다!

user/models에 profile_image랑 cover_image에 default=""을 주니까 테스트는 잘 돌아가네요

2021-12-02 15:01 UTC, jaejae2374 commented
@leejoey0921 default="" 주지 않아도 로컬에서는 테스트 잘 통과했는데 아마 makemigrations 문제였을 것 같습니다. 다시한번 commit 해볼게요

2021-12-02 15:10 UTC, jaejae2374 commented
@IHIHHIHI static 파일 commit 내역 보면 초반에 gitignore에 추가 안해서 폴더가 생성된채로 업데이트가 안되어 있는 것 같은데 맞나요..?

2021-12-03 00:15 UTC, IHIHHIHI commented
@jaejae2374 네. 여전히 그 바뀐 파일들 들어가보면 static 안의 내용들이 보입니다...!

2021-12-03 08:09 UTC, jaejae2374 commented
@IHIHHIHI 수정했습니다.

2021-12-03 11:21 UTC, IHIHHIHI requested changes

2021-12-03 11:21 UTC, IHIHHIHI commented on project/newsfeed/tests.py
> +        #내 게시물이 친구 게시물보다 일찎 생성되었으므로, 친구 게시물이 먼저 떠야함 (최신순)
```suggestion
        #내 게시물이 친구 게시물보다 일찍 생성되었으므로, 친구 게시물이 먼저 떠야함 (최신순)
```

2021-12-03 11:21 UTC, IHIHHIHI commented on project/newsfeed/models.py
> +    likes = models.PositiveIntegerField(default=0)
혹시 좋아요 한 유저의 경우에는 저장하지 않는 것인가요?

2021-12-03 14:02 UTC, jaejae2374 commented on project/newsfeed/models.py
> +    likes = models.PositiveIntegerField(default=0)
@IHIHHIHI 그렇네요 있어야하겠군요..!

2021-12-03 14:07 UTC, jaejae2374 commented on project/newsfeed/models.py
> +    likes = models.PositiveIntegerField(default=0)
그 부분은 준경님이 좋아요 기능 부분 만드실때 모델에 추가하시면 될 거 같슴당 @leejoey0921

2021-12-03 15:44 UTC, leejoey0921 commented on project/newsfeed/views.py
> +    @swagger_auto_schema(request_body=PostListSerializer)
이건 스웨거에서의 request body에 들어갈 field들을 serializer에서 받는 것대로 자동으로 채워달라는 뜻인데,
여기는 GET 요청이라 필요가 없을 것 같네요!
명확하게 말 안해드렸어서 죄송합니다 ㅠ

2021-12-03 15:51 UTC, leejoey0921 commented on project/newsfeed/models.py
> +    likes = models.PositiveIntegerField(default=0)
@IHIHHIHI 좋아요는 민준님이 잘 해주시리라 믿습니다...! 😊😊

2021-12-03 15:58 UTC, leejoey0921 commented on project/newsfeed/views.py
> +    @swagger_auto_schema(request_body=PostListSerializer)
> 

이 줄 하나 삭제했습니다!

2021-12-03 16:17 UTC, jaejae2374 commented on project/newsfeed/models.py
> +    likes = models.PositiveIntegerField(default=0)
아 민준님 담당이었군요

2021-12-05 04:42 UTC, IHIHHIHI approved these changes

2021-12-05 04:43 UTC, IHIHHIHI commented on project/newsfeed/models.py
> +    likes = models.PositiveIntegerField(default=0)
네 필드 하나 더 정의해서 짜볼게요

2021-12-05 05:00 UTC, merged