Feat/friend
wafflestudio19-5/team9-server pull request #47
Opened 2022-01-01 13:42 UTC by leejoey0921

`/user/friend/`  
- DELETE: “friend” field에 친구 id를 받아 로그인된 유저의 친구 목록에서 삭제  
  

`/user/friend/request/`  
- GET: 로그인된 유저가 받은 친구요청 목록을 페이지네이션하여 반환 (요청 보낸 사람의 프로필 정보 포함)
- POST: “receiver” field를 받아 친구 요청 보내기
- PUT: “sender”field를 받아서 자신이 받은 친구 요청 수락하기
- DELETE: “sender”, “receiver”를 모두 받아서 자신이 보냈거나 받은 친구 요청 삭제하기

@jaejae2374 재현님께서 newsfeed/pagination.py의 필요성에 대해 피드백해주셨는데, default pagination의 ordering이 "-created"인 반면 댓글은 "created"순으로 반환해야 했기 때문에 따로 파는 게 맞다고 판단했습니다!

2022-01-01 16:56 UTC, IHIHHIHI requested changes

2022-01-01 16:56 UTC, IHIHHIHI commented on project/user/serializers.py
> +            raise serializers.ValidationError("이 유저에게 친구 요청을 받았습니다.")
```suggestion
            raise serializers.ValidationError("이 유저에게 이미 친구 요청을 받았습니다.")
```
로 고치면 의미가 더 명확할 것 같습니다!

2022-01-01 16:56 UTC, IHIHHIHI commented on project/user/views.py
> +            return Response(status=status.HTTP_400_BAD_REQUEST, data="권한이 없습니다.")
이런 부분의 경우에는 저는 401 unauthorized로 처리했는데 하나로 통일하면 좋을 것 같습니다! 
https://mangkyu.tistory.com/146
더 찾아보니 403으로 하는 것이 맞다네요... ㅜㅜ

2022-01-01 16:56 UTC, IHIHHIHI commented on project/user/views.py
> +        return Response(status=status.HTTP_200_OK, data="삭제 완료되었습니다.")
이런 경우에도 저는 204 no content로 리스폰스 코드를 정했습니다!

2022-01-01 17:16 UTC, leejoey0921 commented on project/user/views.py
> +            return Response(status=status.HTTP_400_BAD_REQUEST, data="권한이 없습니다.")
그렇네요! 여기에는 바로 반영하겠습니다 ㅎㅎ

2022-01-02 01:40 UTC, IHIHHIHI approved these changes
수고하셨습니다!

2022-01-02 01:41 UTC, merged